# permissions for end users to edit imagesyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: imagesync-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sync-controller
    app.kubernetes.io/part-of: sync-controller
    app.kubernetes.io/managed-by: kustomize
  name: imagesync-editor-role
rules:
- apiGroups:
  - sync.controller.rkgcloud.com
  resources:
  - imagesyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sync.controller.rkgcloud.com
  resources:
  - imagesyncs/status
  verbs:
  - get
